name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    call-workflow:
      uses: ShumilinPavel/deploy-ghactions/.github/workflows/test.yml@main

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flex-grid-site"
          heroku_email: "pavelshum10@gmail.com"
